[package]
name = "diesel-async"
version = "0.1.1"
authors = ["Georg Semmler <github@weiznich.de>"]
edition = "2018"
autotests = false
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/weiznich/diesel_async"
keywords = ["orm", "database", "sql"]
categories = ["database"]
description = "An async extension for Diesel the safe, extensible ORM and Query Builder"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", default-features = false, features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"]}
async-trait = "0.1.51"
futures = "0.3.17"
tokio-postgres = { version = "0.7.2", optional = true}
tokio = { version = "1", optional = true}

bb8 = {version = "0.8", optional = true}
deadpool = {version = "0.9", optional = true}
mobc = {version = "0.7", optional = true}
scoped-futures = {version = "0.1", features = ["std"]}

[dev-dependencies]
tokio = {version = "1.12.0", features = ["rt", "macros", "rt-multi-thread"]}
cfg-if = "1"
chrono = "0.4"
diesel = { version = "2.0.0", default-features = false,  features = ["chrono"]}

[features]
default = []
postgres = ["diesel/postgres_backend", "tokio-postgres", "tokio", "tokio/rt"]

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[package.metadata.docs.rs]
features = ["postgres", "deadpool", "bb8", "mobc"]
no-default-features = true
rustc-args = ["--cfg", "doc_cfg"]
rustdoc-args = ["--cfg", "doc_cfg"]
